### PR TITLE
run with docker compose

### PR DESCRIPTION
**Pull request by go-laoji**
Implement #15 

frontend:build as standalone
backend:add environment variables

### CODE REVIEW

**Comment by BlankCheng** [comment]
Hi, thanks for your amazing job! We really appreciate that.
Could you provide the running script for deployment just like in https://github.com/xlang-ai/OpenAgents/blob/main/backend/README.md, so that ppl can follow to deploy it and we can also test it?

**Comment by go-laoji** [comment]
in project dir run 
`docker compose up -d`
will download redis and mongo images;build frontend and backend images

**Comment by BlankCheng** [comment]
Cool! We will test it this weekend and give feedback if any. 
Thanks again for your great participation.

**Comment by av8dtop** [comment]
@go-laoji 
感謝你做docker-compose 我遇到一個問題，
因為我CPU沒有支援aux所以mongo用4.4，
加上使用ubuntu去架設docker，
發生很奇怪的事情就是backend start過沒兩秒就stop ，
而且還沒有任何log可查看很麻煩，
但是用支援aux的筆電windows的docker-desktop部屬倒是沒啥問題，
本來想動手解決，發現沒東西可查，不知從何下手，
不知道是不是真的跟mongo有關嗎? 但是我想想覺得不太可能，
起碼應該可以跑起來出error log才對，
我用過太多docker的狀況沒遇過這情況

**Comment by BlankCheng** [comment]
LGTM!

**Pull request merged**
